Search.appendIndex(
    [
                {
            "fqsen": "\\chillerlan\\HTTP\\ClientException",
            "name": "ClientException",
            "summary": "",
            "url": "classes/chillerlan-HTTP-ClientException.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlClient",
            "name": "CurlClient",
            "summary": "A\u0020\u0022simple\u0022\u0020cURL\u0020http\u0020client",
            "url": "classes/chillerlan-HTTP-CurlClient.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlClient\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlClient.html#method_sendRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle",
            "name": "CurlHandle",
            "summary": "Implements\u0020a\u0020cURL\u0020connection\u0020object",
            "url": "classes/chillerlan-HTTP-CurlHandle.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CurlHandle\u0020constructor.",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "close\u0020an\u0020existing\u0020cURL\u0020handle\u0020on\u0020exit",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method___destruct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "closes\u0020the\u0020handle",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_close"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetCurlResource\u0028\u0029",
            "name": "getCurlResource",
            "summary": "returns\u0020the\u0020internal\u0020cURL\u0020resource\u0020in\u0020its\u0020current\u0020state",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getCurlResource"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetHandleID\u0028\u0029",
            "name": "getHandleID",
            "summary": "returns\u0020the\u0020handle\u0020ID\u0020\u0028cURL\u0020resource\u0020id\u0029",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getHandleID"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "returns\u0020the\u0020result\u0020from\u0020\u0060curl_getinfo\u0028\u0029\u0060\u0020or\u0020\u0060null\u0060\u0020in\u0020case\u0020of\u0020an\u0020error",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getInfo"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getResponse"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetCurlOptions\u0028\u0029",
            "name": "getCurlOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getCurlOptions"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AguessCA\u0028\u0029",
            "name": "guessCA",
            "summary": "Check\u0020default\u0020locations\u0020for\u0020the\u0020CA\u0020bundle",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_guessCA"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AsetCA\u0028\u0029",
            "name": "setCA",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_setCA"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AsetRequestOptions\u0028\u0029",
            "name": "setRequestOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_setRequestOptions"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_init"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003Aexec\u0028\u0029",
            "name": "exec",
            "summary": "executes\u0020the\u0020current\u0020cURL\u0020instance\u0020and\u0020returns\u0020the\u0020error\u0020number",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_exec"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "returns\u0020a\u0020string\u0020containing\u0020the\u0020last\u0020error",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#method_getError"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003ACURL_NETWORK_ERRORS",
            "name": "CURL_NETWORK_ERRORS",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#constant_CURL_NETWORK_ERRORS"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003ANEVER_OVERWRITE",
            "name": "NEVER_OVERWRITE",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#constant_NEVER_OVERWRITE"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024curl",
            "name": "curl",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_curl"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024handleID",
            "name": "handleID",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_handleID"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024curlOptions",
            "name": "curlOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_curlOptions"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024initialized",
            "name": "initialized",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_initialized"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024requestBody",
            "name": "requestBody",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_requestBody"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024responseBody",
            "name": "responseBody",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_responseBody"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_request"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_response"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlHandle\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlHandle.html#property_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient",
            "name": "CurlMultiClient",
            "summary": "Curl\u0020multi\u0020http\u0020client",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CurlMultiClient\u0020constructor.",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003AinitCurlMultiOptions\u0028\u0029",
            "name": "initCurlMultiOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_initCurlMultiOptions"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "close\u0020an\u0020existing\u0020cURL\u0020multi\u0020handle\u0020on\u0020exit",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method___destruct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_setLogger"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "closes\u0020the\u0020handle",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_close"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003AaddRequest\u0028\u0029",
            "name": "addRequest",
            "summary": "adds\u0020a\u0020request\u0020to\u0020the\u0020stack",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_addRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003AaddRequests\u0028\u0029",
            "name": "addRequests",
            "summary": "adds\u0020multiple\u0020requests\u0020to\u0020the\u0020stack",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_addRequests"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "processes\u0020the\u0020stack",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_process"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "resolves\u0020the\u0020handle,\u0020calls\u0020the\u0020response\u0020handler\u0020callback\u0020and\u0020creates\u0020the\u0020next\u0020handle",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_resolve"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003AcreateHandle\u0028\u0029",
            "name": "createHandle",
            "summary": "creates\u0020a\u0020new\u0020request\u0020handle",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#method_createHandle"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024curl_multi",
            "name": "curl_multi",
            "summary": "the\u0020cURL\u0020multi\u0020handle\u0020instance",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_curl_multi"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024requests",
            "name": "requests",
            "summary": "An\u0020array\u0020of\u0020RequestInterface\u0020to\u0020run",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_requests"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024handles",
            "name": "handles",
            "summary": "the\u0020stack\u0020of\u0020running\u0020handles",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_handles"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024counter",
            "name": "counter",
            "summary": "the\u0020request\u0020counter\u0020\u0028request\u0020ID\/order\u0020in\u0020multi\u0020response\u0020handler\u0029",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_counter"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024multiResponseHandler",
            "name": "multiResponseHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_multiResponseHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_responseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\CurlMultiClient\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/chillerlan-HTTP-CurlMultiClient.html#property_logger"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract",
            "name": "HTTPClientAbstract",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HTTPClientAbstract\u0020constructor.",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Sets\u0020a\u0020PSR\u002D3\u0020Logger",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#method_setLogger"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003AsetResponseFactory\u0028\u0029",
            "name": "setResponseFactory",
            "summary": "Sets\u0020a\u0020PSR\u002D17\u0020response\u0020factory",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#method_setResponseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003AsetStreamFactory\u0028\u0029",
            "name": "setStreamFactory",
            "summary": "Sets\u0020a\u0020PSR\u002D17\u0020stream\u0020factory",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#method_setStreamFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#property_streamFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#property_responseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#property_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientAbstract\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientAbstract.html#property_logger"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientInterface",
            "name": "HTTPClientInterface",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPClientInterface.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientInterface\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Sets\u0020a\u0020PSR\u002D3\u0020Logger",
            "url": "classes/chillerlan-HTTP-HTTPClientInterface.html#method_setLogger"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientInterface\u003A\u003AsetResponseFactory\u0028\u0029",
            "name": "setResponseFactory",
            "summary": "Sets\u0020a\u0020PSR\u002D17\u0020response\u0020factory",
            "url": "classes/chillerlan-HTTP-HTTPClientInterface.html#method_setResponseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPClientInterface\u003A\u003AsetStreamFactory\u0028\u0029",
            "name": "setStreamFactory",
            "summary": "Sets\u0020a\u0020PSR\u002D17\u0020stream\u0020factory",
            "url": "classes/chillerlan-HTTP-HTTPClientInterface.html#method_setStreamFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptions",
            "name": "HTTPOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPOptions.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait",
            "name": "HTTPOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003Aset_user_agent\u0028\u0029",
            "name": "set_user_agent",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#method_set_user_agent"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003Aset_curl_options\u0028\u0029",
            "name": "set_curl_options",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#method_set_curl_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003Aset_dns_over_https\u0028\u0029",
            "name": "set_dns_over_https",
            "summary": "",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#method_set_dns_over_https"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024user_agent",
            "name": "user_agent",
            "summary": "A\u0020custom\u0020user\u0020agent\u0020string",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_user_agent"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024curl_options",
            "name": "curl_options",
            "summary": "options\u0020for\u0020each\u0020curl\u0020instance",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_curl_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024ca_info",
            "name": "ca_info",
            "summary": "CA\u0020Root\u0020Certificates\u0020for\u0020use\u0020with\u0020CURL\/SSL",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_ca_info"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024ssl_verifypeer",
            "name": "ssl_verifypeer",
            "summary": "see\u0020CURLOPT_SSL_VERIFYPEER\nrequires\u0020either\u0020HTTPOptions\u003A\u003A\u0024ca_info\u0020or\u0020a\u0020properly\u0020working\u0020system\u0020CA\u0020file",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_ssl_verifypeer"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024curl_multi_options",
            "name": "curl_multi_options",
            "summary": "options\u0020for\u0020the\u0020curl\u0020multi\u0020instance",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_curl_multi_options"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024curl_check_OCSP",
            "name": "curl_check_OCSP",
            "summary": "cURL\u0020extra\u0020hardening",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_curl_check_OCSP"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024window_size",
            "name": "window_size",
            "summary": "maximum\u0020of\u0020concurrent\u0020requests\u0020for\u0020curl_multi",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_window_size"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024sleep",
            "name": "sleep",
            "summary": "sleep\u0020timer\u0020\u0028microseconds\u0029\u0020between\u0020each\u0020fired\u0020multi\u0020request\u0020on\u0020startup",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_sleep"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "Timeout\u0020value",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_timeout"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024retries",
            "name": "retries",
            "summary": "Number\u0020of\u0020retries\u0020\u0028multi\u0020fetch\u0029",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_retries"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\HTTPOptionsTrait\u003A\u003A\u0024dns_over_https",
            "name": "dns_over_https",
            "summary": "Sets\u0020a\u0020DNS\u002Dover\u002DHTTPS\u0020provider\u0020URL",
            "url": "classes/chillerlan-HTTP-HTTPOptionsTrait.html#property_dns_over_https"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\MultiResponseHandlerInterface",
            "name": "MultiResponseHandlerInterface",
            "summary": "The\u0020multi\u0020response\u0020handler.\u0020\u0028Schr\u00F6dinger\u0027s\u0020cat\u0020state\u0020handler\u0029",
            "url": "classes/chillerlan-HTTP-MultiResponseHandlerInterface.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\MultiResponseHandlerInterface\u003A\u003AhandleResponse\u0028\u0029",
            "name": "handleResponse",
            "summary": "This\u0020method\u0020will\u0020be\u0020called\u0020within\u0020a\u0020loop\u0020in\u0020MultiRequest\u003A\u003AprocessStack\u0028\u0029.",
            "url": "classes/chillerlan-HTTP-MultiResponseHandlerInterface.html#method_handleResponse"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\NetworkException",
            "name": "NetworkException",
            "summary": "",
            "url": "classes/chillerlan-HTTP-NetworkException.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\NetworkException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/chillerlan-HTTP-NetworkException.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\NetworkException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTP-NetworkException.html#method_getRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\NetworkException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/chillerlan-HTTP-NetworkException.html#property_request"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\RequestException",
            "name": "RequestException",
            "summary": "",
            "url": "classes/chillerlan-HTTP-RequestException.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\RequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/chillerlan-HTTP-RequestException.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\RequestException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTP-RequestException.html#method_getRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\RequestException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/chillerlan-HTTP-RequestException.html#property_request"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\StreamClient",
            "name": "StreamClient",
            "summary": "A\u0020http\u0020client\u0020via\u0020PHP\u0020streams",
            "url": "classes/chillerlan-HTTP-StreamClient.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\StreamClient\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTP-StreamClient.html#method_sendRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\StreamClient\u003A\u003AgetContextOptions\u0028\u0029",
            "name": "getContextOptions",
            "summary": "",
            "url": "classes/chillerlan-HTTP-StreamClient.html#method_getContextOptions"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\StreamClient\u003A\u003AgetRequestHeaders\u0028\u0029",
            "name": "getRequestHeaders",
            "summary": "",
            "url": "classes/chillerlan-HTTP-StreamClient.html#method_getRequestHeaders"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\StreamClient\u003A\u003AcreateResponse\u0028\u0029",
            "name": "createResponse",
            "summary": "",
            "url": "classes/chillerlan-HTTP-StreamClient.html#method_createResponse"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\CurlClientFactory",
            "name": "CurlClientFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-CurlClientFactory.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\CurlClientFactory\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-CurlClientFactory.html#method_getClient"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\CurlClientNoCAFactory",
            "name": "CurlClientNoCAFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-CurlClientNoCAFactory.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\CurlClientNoCAFactory\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-CurlClientNoCAFactory.html#method_getClient"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\StreamClientFactory",
            "name": "StreamClientFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-StreamClientFactory.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\StreamClientFactory\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-StreamClientFactory.html#method_getClient"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\StreamClientNoCAFactory",
            "name": "StreamClientNoCAFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-StreamClientNoCAFactory.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories\\StreamClientNoCAFactory\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-ClientFactories-StreamClientNoCAFactory.html#method_getClient"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlClientNoCATest",
            "name": "CurlClientNoCATest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlClientNoCATest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlClientNoCATest\u003A\u003A\u0024HTTP_CLIENT_FACTORY",
            "name": "HTTP_CLIENT_FACTORY",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlClientNoCATest.html#property_HTTP_CLIENT_FACTORY"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlClientTest",
            "name": "CurlClientTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlClientTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlClientTest\u003A\u003AtestRequestError\u0028\u0029",
            "name": "testRequestError",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlClientTest.html#method_testRequestError"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlClientTest\u003A\u003A\u0024HTTP_CLIENT_FACTORY",
            "name": "HTTP_CLIENT_FACTORY",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlClientTest.html#property_HTTP_CLIENT_FACTORY"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest",
            "name": "CurlHandleTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AcreateHandle\u0028\u0029",
            "name": "createHandle",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_createHandle"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AinvalidCaOptionProvider\u0028\u0029",
            "name": "invalidCaOptionProvider",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_invalidCaOptionProvider"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestInvalidCAException\u0028\u0029",
            "name": "testInvalidCAException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testInvalidCAException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AcaOptionProvider\u0028\u0029",
            "name": "caOptionProvider",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_caOptionProvider"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestCaInfoFile\u0028\u0029",
            "name": "testCaInfoFile",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testCaInfoFile"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003ArequestMethodProvider\u0028\u0029",
            "name": "requestMethodProvider",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_requestMethodProvider"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestRequestMethods\u0028\u0029",
            "name": "testRequestMethods",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testRequestMethods"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003ArequestMethodWithBodyProvider\u0028\u0029",
            "name": "requestMethodWithBodyProvider",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_requestMethodWithBodyProvider"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestRequestMethodsWithFormBody\u0028\u0029",
            "name": "testRequestMethodsWithFormBody",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testRequestMethodsWithFormBody"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestRequestMethodsWithJsonBody\u0028\u0029",
            "name": "testRequestMethodsWithJsonBody",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testRequestMethodsWithJsonBody"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003AtestLargeBody\u0028\u0029",
            "name": "testLargeBody",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#method_testLargeBody"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlHandleTest\u003A\u003A\u0024HTTP_CLIENT_FACTORY",
            "name": "HTTP_CLIENT_FACTORY",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlHandleTest.html#property_HTTP_CLIENT_FACTORY"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest",
            "name": "CurlMultiClientTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003AgetTestResponseHandler\u0028\u0029",
            "name": "getTestResponseHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#method_getTestResponseHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003AgetRequests\u0028\u0029",
            "name": "getRequests",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#method_getRequests"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003AtestMultiRequest\u0028\u0029",
            "name": "testMultiRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#method_testMultiRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003AtestEmptyStackException\u0028\u0029",
            "name": "testEmptyStackException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#method_testEmptyStackException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003A\u0024http",
            "name": "http",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#property_http"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\CurlMultiClientTest\u003A\u003A\u0024multiResponseHandler",
            "name": "multiResponseHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-CurlMultiClientTest.html#property_multiResponseHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPClientTestAbstract",
            "name": "HTTPClientTestAbstract",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPClientTestAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPClientTestAbstract\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPClientTestAbstract.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPClientTestAbstract\u003A\u003AtestSendRequest\u0028\u0029",
            "name": "testSendRequest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPClientTestAbstract.html#method_testSendRequest"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPClientTestAbstract\u003A\u003AtestNetworkError\u0028\u0029",
            "name": "testNetworkError",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPClientTestAbstract.html#method_testNetworkError"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPClientTestAbstract\u003A\u003AUSER_AGENT",
            "name": "USER_AGENT",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPClientTestAbstract.html#constant_USER_AGENT"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPOptionsTest",
            "name": "HTTPOptionsTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPOptionsTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPOptionsTest\u003A\u003AtestInvalidUserAgentException\u0028\u0029",
            "name": "testInvalidUserAgentException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPOptionsTest.html#method_testInvalidUserAgentException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPOptionsTest\u003A\u003AtestSetDnsOverHttpsURL\u0028\u0029",
            "name": "testSetDnsOverHttpsURL",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPOptionsTest.html#method_testSetDnsOverHttpsURL"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\HTTPOptionsTest\u003A\u003AtestSetDnsOverHttpsURLException\u0028\u0029",
            "name": "testSetDnsOverHttpsURLException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-HTTPOptionsTest.html#method_testSetDnsOverHttpsURLException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\StreamClientNoCATest",
            "name": "StreamClientNoCATest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-StreamClientNoCATest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\StreamClientNoCATest\u003A\u003A\u0024HTTP_CLIENT_FACTORY",
            "name": "HTTP_CLIENT_FACTORY",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-StreamClientNoCATest.html#property_HTTP_CLIENT_FACTORY"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\StreamClientTest",
            "name": "StreamClientTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-StreamClientTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\StreamClientTest\u003A\u003A\u0024HTTP_CLIENT_FACTORY",
            "name": "HTTP_CLIENT_FACTORY",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-StreamClientTest.html#property_HTTP_CLIENT_FACTORY"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP",
            "name": "HTTP",
            "summary": "",
            "url": "namespaces/chillerlan-http.html"
        },                {
            "fqsen": "\\chillerlan",
            "name": "chillerlan",
            "summary": "",
            "url": "namespaces/chillerlan.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\ClientFactories",
            "name": "ClientFactories",
            "summary": "",
            "url": "namespaces/chillerlan-httptest-clientfactories.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest",
            "name": "HTTPTest",
            "summary": "",
            "url": "namespaces/chillerlan-httptest.html"
        }            ]
);
